project:
  type: website
  output-dir: docs

website:
  title: "Cael_DSPG24_Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/caelliastate
      - icon: twitter
        href: https://twitter.com/CaelLeistikow
format:
  html:
    theme: cosmo
    css: styles.css



